name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            echo "No package-lock.json found, skipping npm install"
          fi

      - name: Build project
        run: |
          # Add any build steps if needed
          echo "Building project..."
          
          # Validate HTML, CSS, JS files
          echo "Validating files..."
          
          # Check if required files exist
          if [ ! -f index.html ]; then
            echo "Error: index.html not found"
            exit 1
          fi
          
          if [ ! -f css/style.css ]; then
            echo "Error: css/style.css not found"
            exit 1
          fi
          
          if [ ! -f js/main.js ]; then
            echo "Error: js/main.js not found"
            exit 1
          fi
          
          echo "All required files found"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4